on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  automerge:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Extract branch name
      uses: mdecoleman/pr-branch-name@2.0.0
      id: extract_branch
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge develop -> staging
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: ${{ steps.extract_branch.outputs.branch }}
        target_branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge development -> quality
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: develop
        target_branch: quality
        github_token: ${{ secrets.GITHUB_TOKEN }}

